### ISSUE TITLE
TODO:

### ISSUE THREAD

**Issue by mkong0216** [mkong0216/PriCoSha#1]
- [x] Let user who created content to edit content
- [x] Let user who created content delete content
- [x] If user changes content to public, does that remove the content from Share? (Can an item be both public and shared to a FriendGroup?)
- [x] List members of FriendGroups that user is a member of 
- [x] Show success message when user has successfully tagged someone ("Tag needs approval")
- [x] Filter content user can see by group it is shared from  (Check group_name and group creator's username)
- [x] If content shared to multiple groups user is a part of, show both groups in "Shared From:" but not duplicate content image
- [x] Allow creator of content to share content to other groups after creating content (should users who can see content also be able to share the content?)

**Comment by mkong0216** [comment]
Currently if user changes content to public, content is still shared to original FriendGroups. A new "public" tag is added to the content on the home page.
